name: 服务器游玩反馈
description: 这里不让空着所以随便写点
labels: []
projects: []
assignees:
  - 'RaTaiHok'
body:
  - type: input
    id: user_name
    attributes:
      label: 玩家名
      description: 请输入你在服务器中的玩家名
      placeholder: ex. RTHsama
    validations:
      required: true

  - type: dropdown
    id: feedback_type
    attributes:
      label: 反馈类型
      description: 请选择反馈类型
      options:
        - Bug反馈
        - 建议
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### 如果您选择了 **Bug反馈**，请填写以下内容：

  - type: input
    id: game_version
    attributes:
      label: 游戏版本和客户端
      description: 请输入你使用的mc版本和客户端
      placeholder: ex. 1.20.1 Fabric
    validations:
      required: false

  - type: textarea
    id: mod_list
    attributes:
      label: Mod列表
      description: 请输入你使用的Mod列表
      placeholder: 请列出所有安装的Mod
    validations:
      required: false

  - type: textarea
    id: bug_log
    attributes:
      label: Bug日志
      description: 请提供bug发生时的日志
      placeholder: 复制粘贴你的日志内容
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### 如果您选择了 **建议**，请填写以下内容：

  - type: textarea
    id: suggestion
    attributes:
      label: 想法或建议
      description: 请尽情提出您的想法或建议
      placeholder: ~
    validations:
      required: false
